name = "terminal-2"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 데이터베이스 바인딩
# wrangler d1 create terminal-db 실행 후 생성된 database_id를 입력할 것
[[d1_databases]]
binding = "DB"
database_name = "terminal-db"
database_id = "42d83d1e-e0ee-42af-91ff-d57c2387bb45"
migrations_dir = "migrations"
